export const EVENT_CATEGORIES = [
  "Corporate Actions & Shareholder Returns",
  "Capital Raising & Securities Issuance",
  "Ownership, Promoter & Control",
  "Financial Results & Reporting",
  "Operating Metrics & Business Updates",
  "Business Growth, Orders & Operations",
  "M&A, Investments & Restructuring",
  "Credit, Debt & Liquidity",
  "Governance & Leadership",
  "Legal, Regulatory & Fraud",
  "Market Surveillance & Trading Signals",
  "Shareholder Meetings & Investor Communication",
  "Compliance & Securities Administration",
  "Macro & Economy",
  "Others",
] as const;

/** Short names for category pills on article cards */
export const CATEGORY_SHORT_NAMES: Record<string, string> = {
  "Corporate Actions & Shareholder Returns": "Corporate Actions",
  "Capital Raising & Securities Issuance": "Capital Raising",
  "Ownership, Promoter & Control": "Ownership & Control",
  "Financial Results & Reporting": "Financial Results",
  "Operating Metrics & Business Updates": "Operating Metrics",
  "Business Growth, Orders & Operations": "Business Growth",
  "M&A, Investments & Restructuring": "M&A, Investments",
  "Credit, Debt & Liquidity": "Debt & Liquidity",
  "Governance & Leadership": "Governance",
  "Legal, Regulatory & Fraud": "Legal",
  "Market Surveillance & Trading Signals": "Market Pulse",
  "Shareholder Meetings & Investor Communication": "Shareholder Comms",
  "Compliance & Securities Administration": "Compliance",
  "Macro & Economy": "Macro",
  "Others": "Others",
};

export const INDUSTRY_SECTORS = [
  "Agriculture & Agri Inputs",
  "Chemicals",
  "Consumer Discretionary",
  "Consumer Staples",
  "Energy & Utilities",
  "Financial Services",
  "Healthcare & Pharmaceuticals",
  "Industrials & Business Services",
  "Materials",
  "Real Estate",
  "Technology",
  "Telecom & Media",
  "Textiles & Apparel",
  "Transportation & Logistics",
  "Others",
] as const;
