export const EVENT_CATEGORIES = [
  "Corporate Actions & Shareholder Returns",
  "Capital Raising & Securities Issuance",
  "Ownership, Promoter & Control",
  "Financial Results & Reporting",
  "Operating Metrics & Business Updates",
  "Business Growth, Orders & Operations",
  "M&A, Investments & Restructuring",
  "Credit, Debt & Liquidity",
  "Governance & Leadership",
  "Legal, Regulatory & Fraud",
  "Market Surveillance & Trading Signals",
  "Shareholder Meetings & Investor Communication",
  "Compliance & Securities Administration",
  "Macro & Economy",
  "Others",
] as const;

export const INDUSTRY_SECTORS = [
  "Agriculture & Agri Inputs",
  "Chemicals",
  "Consumer Discretionary",
  "Consumer Staples",
  "Energy & Utilities",
  "Financial Services",
  "Healthcare & Pharmaceuticals",
  "Industrials & Business Services",
  "Materials",
  "Real Estate",
  "Technology",
  "Telecom & Media",
  "Textiles & Apparel",
  "Transportation & Logistics",
  "Others",
] as const;
